{% set version = "0.3.0" %}

package:
  name: plasmapy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/plasmapy/plasmapy-{{ version }}.tar.gz
  sha256: 0b0a78f71635c873b536e884ea0ce35d25b0358415b222a36876f92a42481cf7

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vvv"
  skip: True    # [py < 36]

requirements:
  host:
    - python
    - pip
    - setuptools
    - numpy >=1.14
    - scipy >=0.19
    - astropy >=3.1
    - colorama >=0.3
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.19
    - astropy >=3.1
    - colorama >=0.3
    - pytest >= 5.1
    - mpmath >=1.0
    - h5py >=2.8
    - lmfit >=0.9.7
    - matplotlib >=2.0
    - pytest-astropy

test:
  imports:
    - plasmapy
    - plasmapy.atomic
    - plasmapy.classes
    - plasmapy.mathematics
    - plasmapy.physics
    - plasmapy.transport
    - plasmapy.utils
  commands:
    - python -c "import plasmapy, sys; sys.exit(plasmapy.test())"
    - pytest --pyargs plasmapy

about:
  home: https://github.com/PlasmaPy/PlasmaPy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Python package for plasma physics
  description: 'PlasmaPy is a community-developed and community-driven Python package for plasma physics.'
  doc_url: 'http://plasmapy.readthedocs.io/en/docs/'
  dev_url: 'https://github.com/plasmapy/plasmapy'

extra:
  recipe-maintainers:
    - SolarDrew
    - StanczakDominik
