{% set version = "0.8.1" %}

package:
  name: plasmapy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/plasmapy/plasmapy-{{ version }}.tar.gz
  sha256: cc068e0fbc2e36d6192c89811b5ff3495097ba3c879dcf44326aeae3fd259924

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
    - numpy >=1.19.0, <1.22
    - setuptools >=41.2
    - setuptools_scm
    - wheel >=0.29.0
  run:
    - python >=3.8
    - numpy >=1.19.0, <1.22
    - astropy >=4.3.1
    - cached-property >=1.5.2
    - h5py >=3.0.0
    - ipywidgets >=7.6.5
    - lmfit >=1.0.0
    - matplotlib-base >=3.3.0
    - mpmath >=1.2.1
    - numba
    - packaging
    - pandas >=1.0.0
    - scipy >=1.5.0
    - tqdm >=4.41.0
    - voila
    - xarray >=0.15.0

test:
  imports:
    - plasmapy
    - plasmapy.analysis
    - plasmapy.diagnostics
    - plasmapy.dispersion
    - plasmapy.formulary
    - plasmapy.particles
    - plasmapy.plasma
    - plasmapy.simulation
    - plasmapy.utils
  commands:
    - pytest --pyargs plasmapy -k "not test_grid_methods"
  requires:
    - hypothesis
    - pytest
    - pytest-regressions

about:
  home: https://github.com/PlasmaPy/PlasmaPy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Python package for plasma science
  description: PlasmaPy is a community-developed Python package for plasma research and education.
  doc_url: http://docs.plasmapy.org/en/stable
  dev_url: https://github.com/PlasmaPy/plasmapy

extra:
  recipe-maintainers:
    - StanczakDominik
    - rocco8773
    - namurphy
