{% set version = "0.8.1" %}

package:
  name: plasmapy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/plasmapy/plasmapy-{{ version }}.tar.gz
  sha256: cc068e0fbc2e36d6192c89811b5ff3495097ba3c879dcf44326aeae3fd259924

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
    - setuptools_scm
    - numpy >=1.18.1
  run:
    - python >=3.7
    - {{ pin_compatible('numpy') }}
    - scipy >=1.2
    - astropy >=4.0
    - mpmath >=1.0
    - h5py >=2.8
    - lmfit >=0.9.7
    - matplotlib-base >=2.0
    - pandas >=1.0
    - xarray >=0.14
    - cached-property >=1.5.2
    - tqdm >=4.41.0
    - hypothesis
    - pytest-regressions

test:
  imports:
    - plasmapy
    - plasmapy.particles
    - plasmapy.plasma
    - plasmapy.formulary
    - plasmapy.utils
    - plasmapy.diagnostics
    - plasmapy.simulation
  commands:
    - pytest --pyargs plasmapy -k "not test_grid_methods"
  requires:
    - pytest

about:
  home: https://github.com/PlasmaPy/PlasmaPy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Python package for plasma physics
  description: PlasmaPy is a community-developed and community-driven Python package for plasma physics.
  doc_url: http://plasmapy.readthedocs.io/en/docs/
  dev_url: https://github.com/plasmapy/plasmapy

extra:
  recipe-maintainers:
    - StanczakDominik
    - rocco8773
