{% set python_min = "3.11" %}
{% set version = "2025.8.0" %}

package:
  name: plasmapy
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/plasmapy/plasmapy-{{ version }}.tar.gz
  sha256: b26e6237000d8b69ffb98baa3f3d6043eb6c1828a3d0a1b44ff4053cf61afb90

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - numpy >=1.25
    - setuptools >=61.2
    - setuptools_scm >=6.3.2
    - wheel >=0.37
  run:
    - python >={{ python_min }}
    - astropy-base >=6
    - h5py >=3.8
    - lmfit >=1.1
    - matplotlib-base >=3.7
    - mpmath >=1.3
    - numpy >=1.25
    - packaging >=22
    - pandas >=2
    - scipy >=1.10
    - tqdm >=4.65
    - wrapt >=1.15
    - xarray >=2023.7

test:
  requires:
    - python {{ python_min }}
  imports:
    - plasmapy
    - plasmapy.analysis
    - plasmapy.diagnostics
    - plasmapy.dispersion
    - plasmapy.formulary
    - plasmapy.particles
    - plasmapy.plasma
    - plasmapy.simulation
    - plasmapy.utils

about:
  home: https://github.com/PlasmaPy/PlasmaPy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Python package for plasma science
  description: PlasmaPy is a community-developed Python package for plasma research and education.
  doc_url: http://docs.plasmapy.org/en/stable
  dev_url: https://github.com/PlasmaPy/PlasmaPy

extra:
  recipe-maintainers:
    - StanczakDominik
    - rocco8773
    - namurphy
