{% set python_min = "3.12" %}
{% set version = "2025.10.0" %}

package:
  name: plasmapy
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/plasmapy/plasmapy-{{ version }}.tar.gz
  sha256: cfeb6f2785906e080977292e9b7f3bb6e71cdd8ef7273a877959a113d9e56295

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - numpy >=1.26
    - setuptools >=77
    - setuptools_scm >=8.1
    - wheel >=0.43
  run:
    - python >={{ python_min }}
    - astropy-base >=6
    - h5py >=3.11
    - lmfit >=1.3
    - matplotlib-base >=3.8
    - mpmath >=1.3
    - numpy >=1.26
    - packaging >=24
    - pandas >=2.1.4
    - requests >=2.30
    - scipy >=1.11
    - tqdm >=4.65
    - wrapt >=1.15
    - xarray >=2024.5

test:
  requires:
    - python {{ python_min }}
  imports:
    - plasmapy
    - plasmapy.analysis
    - plasmapy.diagnostics
    - plasmapy.dispersion
    - plasmapy.formulary
    - plasmapy.particles
    - plasmapy.plasma
    - plasmapy.simulation
    - plasmapy.utils

about:
  home: https://github.com/PlasmaPy/PlasmaPy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Python package for plasma science
  description: PlasmaPy is a community-developed Python package for plasma research and education.
  doc_url: https://docs.plasmapy.org/en/stable
  dev_url: https://github.com/PlasmaPy/PlasmaPy

extra:
  recipe-maintainers:
    - rocco8773
    - namurphy
