{% set python_min = '3.10' %}
{% set version = "2024.10.0" %}

package:
  name: plasmapy
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/plasmapy/plasmapy-{{ version }}.tar.gz
  sha256: 5219148202c146e8fc1e14b8707a7e8ca44224a231070643fec4c0fb45c12fb9

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - numpy >=1.23.0
    - setuptools >=61.2.0
    - setuptools_scm >=6.3.2
    - wheel >=0.37.0
  run:
    - python >={{ python_min }}
    - astropy-base >=5.1
    - h5py >=3.7.0
    - ipywidgets >=7.7.0
    - lmfit >=1.1.0
    - matplotlib-base >=3.5.1
    - mpmath >=1.2.1
    - numba >=0.57.0
    - numpy >=1.23.0
    - packaging >=22.0
    - pandas >=1.4.0
    - scipy >=1.8.0
    - tqdm >=4.60.0
    - voila >=0.4.0
    - wrapt >=1.14.0
    - xarray >=2022.3.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - plasmapy
    - plasmapy.analysis
    - plasmapy.diagnostics
    - plasmapy.dispersion
    - plasmapy.formulary
    - plasmapy.particles
    - plasmapy.plasma
    - plasmapy.simulation
    - plasmapy.utils

about:
  home: https://github.com/PlasmaPy/PlasmaPy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Python package for plasma science
  description: PlasmaPy is a community-developed Python package for plasma research and education.
  doc_url: http://docs.plasmapy.org/en/stable
  dev_url: https://github.com/PlasmaPy/PlasmaPy

extra:
  recipe-maintainers:
    - StanczakDominik
    - rocco8773
    - namurphy
