{% set version = "0.6.0" %}

package:
  name: plasmapy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/plasmapy/plasmapy-{{ version }}.tar.gz
  sha256: 77c299c25b844a5cd77d01b5c92223606df72529f85ea1624633741f36216882

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - setuptools_scm
    - numpy >=1.14
  run:
    - python >=3.6
    - {{ pin_compatible('numpy') }}
    - scipy >=0.19
    - astropy >=3.1
    - mpmath >=1.0
    - h5py >=2.8
    - lmfit >=0.9.7
    - matplotlib-base >=2.0
    - pandas >=1.0
    - xarray >=0.14
    - cached-property >=1.5.2
    - tqdm >=4.56.0

test:
  imports:
    - plasmapy
    - plasmapy.particles
    - plasmapy.plasma
    - plasmapy.formulary
    - plasmapy.utils
    - plasmapy.diagnostics
    - plasmapy.simulation
  commands:
    - pytest --pyargs plasmapy
  requires:
    - pytest

about:
  home: https://github.com/PlasmaPy/PlasmaPy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Python package for plasma physics
  description: PlasmaPy is a community-developed and community-driven Python package for plasma physics.
  doc_url: http://plasmapy.readthedocs.io/en/docs/
  dev_url: https://github.com/plasmapy/plasmapy

extra:
  recipe-maintainers:
    - SolarDrew
    - StanczakDominik
    - rocco8773
